# cargo-about settings for THIRD-PARTY-NOTICES.txt. CI fails a change that
# brings in a crate under any other license, and the release uses the same
# file, so the two cannot disagree.
accepted = ["MIT", "Apache-2.0", "Zlib", "Unicode-3.0"]
targets = ["x86_64-pc-windows-msvc"]
ignore-build-dependencies = true
ignore-dev-dependencies = true
