//! Regenerates `src/width_tables.rs` from the Unicode Character Database.
//!
//! ```text
//! cargo run -p vt --example gen_unicode -- <ucd-dir> [out-file]
//! ```
//!
//! `<ucd-dir>` must contain `EastAsianWidth.txt`,
//! `DerivedGeneralCategory.txt`, `GraphemeBreakProperty.txt` and
//! `emoji-data.txt` from one UCD release.
//!
//! Every code point gets one property byte; `src/width.rs` decodes it and
//! the bit layout below must match the constants there:
//!
//! - bits 0-1: width class (0 zero, 1 narrow, 2 wide, 3 East Asian ambiguous)
//! - bits 2-5: grapheme cluster break class
//! - bit 6: Extended_Pictographic
//! - bit 7: Emoji

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs, process};

const CODE_POINTS: usize = 0x11_0000;

const W_ZERO: u8 = 0;
const W_WIDE: u8 = 2;
const W_AMBIGUOUS: u8 = 3;
const GCB_SHIFT: u8 = 2;
const EXT_PICT: u8 = 1 << 6;
const EMOJI: u8 = 1 << 7;

fn main() {
    let mut args = env::args_os().skip(1);
    let Some(dir) = args.next().map(PathBuf::from) else {
        eprintln!("usage: gen_unicode <ucd-dir> [out-file]");
        process::exit(2);
    };
    let out = args.next().map_or_else(
        || Path::new(env!("CARGO_MANIFEST_DIR")).join("src/width_tables.rs"),
        PathBuf::from,
    );

    let mut width = vec![1u8; CODE_POINTS];
    let mut flags = vec![0u8; CODE_POINTS];
    let mut gcb = vec![0u8; CODE_POINTS];

    let eaw = read(&dir, "EastAsianWidth.txt");
    for (r, v) in entries(&eaw) {
        match v {
            "W" | "F" => width[r].fill(W_WIDE),
            "A" => width[r].fill(W_AMBIGUOUS),
            _ => {}
        }
    }

    let emoji = read(&dir, "emoji-data.txt");
    for (r, v) in entries(&emoji) {
        match v {
            "Emoji_Presentation" => width[r].fill(W_WIDE),
            "Extended_Pictographic" => flags[r].iter_mut().for_each(|f| *f |= EXT_PICT),
            "Emoji" => flags[r].iter_mut().for_each(|f| *f |= EMOJI),
            _ => {}
        }
    }

    // Marks, format characters and controls take no cell of their own,
    // whatever their East Asian width says.
    let gc = read(&dir, "DerivedGeneralCategory.txt");
    for (r, v) in entries(&gc) {
        if matches!(v, "Mn" | "Me" | "Cf" | "Cc" | "Cs" | "Zl" | "Zp") {
            width[r].fill(W_ZERO);
        }
    }
    // Terminals draw the soft hyphen as a visible hyphen.
    width[0xAD] = 1;

    let gbp = read(&dir, "GraphemeBreakProperty.txt");
    for (r, v) in entries(&gbp) {
        let class = match v {
            "Extend" => 1,
            "ZWJ" => 2,
            "SpacingMark" => 3,
            "Prepend" => 4,
            "Regional_Indicator" => 5,
            "L" => 6,
            "V" => 7,
            "T" => 8,
            "LV" => 9,
            "LVT" => 10,
            "CR" | "LF" | "Control" => 11,
            _ => fail(&format!("unknown grapheme break class {v}")),
        };
        // Hangul medial vowels and final consonants only ever extend a
        // syllable.
        if matches!(v, "V" | "T") {
            width[r.clone()].fill(W_ZERO);
        }
        gcb[r].fill(class);
    }

    let props: Vec<u8> = (0..CODE_POINTS)
        .map(|i| width[i] | (gcb[i] << GCB_SHIFT) | flags[i])
        .collect();

    // Two-stage lookup: STAGE1 maps a block of code points to a unique
    // block in STAGE2. Pick the block size that gives the smallest tables.
    let (shift, stage1, stage2) = (4..=10)
        .map(|shift| split(&props, shift))
        .min_by_key(|(shift, s1, s2)| s1.len() * index_bytes(s2.len() >> shift) + s2.len())
        .unwrap_or_else(|| fail("no table layout"));
    let blocks = stage2.len() >> shift;

    let mut src = String::new();
    let version = eaw
        .lines()
        .next()
        .and_then(|l| l.strip_prefix("# EastAsianWidth-"))
        .and_then(|l| l.strip_suffix(".txt"))
        .unwrap_or_else(|| fail("EastAsianWidth.txt has no version header"));
    let year = eaw
        .lines()
        .find_map(|l| l.strip_prefix("# © ").and_then(|l| l.get(..4)))
        .unwrap_or("2025");
    let _ = write!(
        src,
        "\
// Generated by `cargo run -p vt --example gen_unicode`. Do not edit.
//
// Derived from the Unicode Character Database {version}
// (https://www.unicode.org/Public/{version}/ucd/): EastAsianWidth.txt,
// DerivedGeneralCategory.txt, GraphemeBreakProperty.txt and
// emoji/emoji-data.txt.
//
// Copyright © 1991-{year} Unicode, Inc. Distributed under the Unicode
// License v3: https://www.unicode.org/license.txt

pub const SHIFT: u32 = {shift};
"
    );
    let ty = if blocks <= 256 { "u8" } else { "u16" };
    array(&mut src, "STAGE1", ty, &stage1);
    let stage2: Vec<usize> = stage2.iter().map(|&b| usize::from(b)).collect();
    array(&mut src, "STAGE2", "u8", &stage2);

    fs::write(&out, src).unwrap_or_else(|e| fail(&format!("{}: {e}", out.display())));
    println!(
        "{}: shift {shift}, {} + {} bytes",
        out.display(),
        stage1.len() * index_bytes(blocks),
        stage2.len()
    );
}

fn read(dir: &Path, name: &str) -> String {
    let path = dir.join(name);
    fs::read_to_string(&path).unwrap_or_else(|e| fail(&format!("{}: {e}", path.display())))
}

/// Yields `(range, value)` for each `XXXX[..YYYY] ; value # comment` line.
fn entries(text: &str) -> impl Iterator<Item = (std::ops::RangeInclusive<usize>, &str)> {
    text.lines().filter_map(|line| {
        let data = line.split('#').next()?.trim();
        let (range, value) = data.split_once(';')?;
        let (lo, hi) = range
            .trim()
            .split_once("..")
            .unwrap_or((range.trim(), range.trim()));
        let hex = |s: &str| {
            usize::from_str_radix(s, 16)
                .unwrap_or_else(|_| fail(&format!("bad code point in {line:?}")))
        };
        Some((hex(lo)..=hex(hi), value.trim()))
    })
}

/// Splits `props` into blocks of `1 << shift` entries and deduplicates them.
fn split(props: &[u8], shift: u32) -> (u32, Vec<usize>, Vec<u8>) {
    let mut seen: HashMap<&[u8], usize> = HashMap::new();
    let mut stage2 = Vec::new();
    let stage1 = props
        .chunks(1 << shift)
        .map(|block| {
            *seen.entry(block).or_insert_with(|| {
                stage2.extend_from_slice(block);
                (stage2.len() >> shift) - 1
            })
        })
        .collect();
    (shift, stage1, stage2)
}

fn index_bytes(blocks: usize) -> usize {
    if blocks <= 256 { 1 } else { 2 }
}

fn array(src: &mut String, name: &str, ty: &str, values: &[usize]) {
    let _ = write!(src, "\npub static {name}: [{ty}; {}] = [", values.len());
    for (i, v) in values.iter().enumerate() {
        if i % 20 == 0 {
            src.push_str("\n   ");
        }
        let _ = write!(src, " {v},");
    }
    src.push_str("\n];\n");
}

fn fail(msg: &str) -> ! {
    eprintln!("gen_unicode: {msg}");
    process::exit(1);
}
